version: '3'
services:
  mysql:
    build:
      context: docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - ./tmp/mysql:/var/lib/mysql:rw
    ports:
      - "3316:3306"

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
      - ./tmp/php-fpm/logs:/usr/local/var/log:rw

  nginx:
    build:
      context: docker/nginx
    ports:
      - 8090:8080
    volumes:
      - ./src:/var/www/html
      - ./tmp/nginx/logs:/var/log/nginx:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - ${HTTP_PHPMYADMIN}:80
    volumes:
       - /sessions
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"